---
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.14.0
    hooks:
      - id: markdownlint
        args:
          - --ignore LICENSE.md
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.15.0
    hooks:
      - id: yamllint
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.4
    hooks:
      - id: shell-lint
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
      - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.12.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        args:
          - --line-length=80
