---
dist: xenial

matrix:
  include:
    - language: python
      python: 3.7
      services: docker
      install:
        - pip install --upgrade pip setuptools molecule docker wheel
      script:
        - find . -name "*.yml" -exec yamllint {} \;
        - molecule test
    - language: ruby
      install:
        - gem install mdl
      script:
        - find . -name "*.md" -and -not -name "LICENSE.md" -exec mdl {} \;
