---
dist: xenial

matrix:
  include:
    - language: python
      python: 3.7
      services: docker
      install:
        - pip install --upgrade -r requirements-test.txt
      script:
        - pre-commit run --all-files
        - molecule test
    - language: ruby
      install:
        - gem install mdl
      script:
        - find . -name "*.md" -and -not -name "LICENSE.md" -exec mdl {} \;
